name: Bug report
description: Bug report
labels: [bug, triage]
body:
- type: markdown
  attributes:
    value: |
      - Write a descriptive bug title above.
      - Search [open](https://github.com/My-Virtual-Worlds/My-OpenSim-Reworked-082x/issues?q=is%3Aopen+label%3Abug+is%3Aissue) bugs to ensure that the issue has not already been identified.

- type: textarea
  attributes:
    label: Environment
    description: About Virtual World Platform Text
    placeholder: ex. OpenSim 0.8.2.1 (64bit) ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: Explain the problem.
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction steps
    description: Steps to reproduce this bug
    placeholder: |
      1. First step
      2. Second step
      Expected: ...
      Actual: ...
  validations:
    required: true
