name: .msbuild48

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cs'
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'My-Virtual-Worlds/My-OpenSim-Reworked-082x'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: shortsha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"   
    - name: preBuild
      run: bash ${GITHUB_WORKSPACE}/runprebuild48.sh

    - name: Build
      id: build
      run: msbuild /p:Configuration=Release OpenSim.sln

    - name: release
      if: success()
      run: zip -r LastBuild.zip bin ThirdPartyLicenses README.md CONTRIBUTORS.txt LICENSE.txt 
    - uses: softprops/action-gh-release@v2
      if: success()
      with:
          tag_name: r${{ steps.vars.outputs.sha_short }}
          name: LastAutoBuild
          files: LastBuild.zip